### ISSUE TITLE
Когда продолжение?

### ISSUE THREAD

**Issue by Borzoff** [t0digital/thanks#27]

**Comment by IgorVolochay** [comment]
Нового года не будет, донатная система приняла Ислам 🤧

**Comment by filimonic** [comment]
Расскажи почему. 
Мне кажется что принятие решения о сворачивании продукта - важная часть жизненного цикла продукта.
Если санкции, то почему бы не поиграть с интеграцией с Киви, Бетховеном, СБП-МИР.

**Comment by Borzoff** [comment]
В телеграме диджитализируй появилась информация по системы донатов
